#!/usr/bin/env python


# usaturnblog build configuration file.
#
# Note that not all possible configuration values are present in this file.
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys

# -- General Sphinx Options ----------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "maatlog",
    "sphinx_copybutton",
]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
root_doc = "index"

# General information about the project.
project = "星のダンスを見においで"
copyright = "2012～2026, usaturn"
author = "usaturn"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = ""
# The full version, including alpha/beta/rc tags.
release = ""

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "ja"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    ".venv",
    ".git",
    "__pycache__",
    "_website",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Maatlog Options -------------------------------------------------------

maatlog_timezone = "Asia/Tokyo"

maatlog_tags = {
    "ubuntu": "Ubuntu",
    "linux": "Linux",
    "resonite": "Resonite",
    "vr": "VR",
    "gentoo": "Gentoo",
    "container": "Container",
    "kvm": "KVM",
    "libvirt": "libvirt",
    "qemu": "QEMU",
    "videogame": "Videogame",
    "cli": "CLI",
    "development": "Development",
    "pyhack": "pyhack",
    "python": "Python",
    "sphinx": "Sphinx",
    "it-study-group": "IT勉強会",
    "memo": "備忘録",
}

maatlog_categories = {
    "it-technology": "IT Technology",
    "linux": "Linux",
    "other": "Other",
    "virtualization": "Virtualization",
    "misc": "駄文",
}

maatlog_authors = {
    "usaturn": "usaturn",
}

maatlog_archive_docname = "blog"
maatlog_page_size = 10
maatlog_generate_feeds = True
maatlog_feed_taxonomies = ("tag", "category", "author", "month")
maatlog_feed_limit = 20


# -- Options for HTML output ----------------------------------------------

html_baseurl = "https://blog.usaturn.net/"

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "maatlog-default"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "images/usaturn_logo.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "images/usaturn_icon.png"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# A list of CSS files to include after the built-in stylesheets.
html_css_files = ["custom.css"]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = "%Y/%m/%d"

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
html_search_language = "ja"

# Output file base name for HTML help builder.
htmlhelp_basename = "usaturnblogdoc"

# -- directive/role definition ------------------------------------------------>
from docutils.parsers.rst.directives.admonitions import BaseAdmonition
from docutils import nodes


class NamedNoteDirective(BaseAdmonition):
    node_class = nodes.admonition
    css_class = 'note'
    #required_arguments = 1
    required_arguments = 0
    optional_arguments = 1

    def run(self):
        title = u''
        if self.arguments:
            title += self.arguments[0]

        if 'class' in self.options:
            self.options['class'].append(self.css_class)
        else:
            self.options['class'] = [self.css_class]


        node = self.node_class('\n'.join(self.content))
        node += nodes.title(title, title)
        node['classes'] += self.options['class']
        node['name'] = self.name
        self.state.nested_parse(self.content, self.content_offset, node)

        return [node]


class ColumnDirective(NamedNoteDirective):
    css_class = 'column'


def setup(app):
    app.add_directive('column', ColumnDirective)
